name: SimpleSAC
channels:
    - https://conda.anaconda.org/pytorch
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - jupyter
    - patchelf
    - pytorch=1.12.0
    - cudatoolkit=11.3
    - pip:
        - Cython
        - tqdm
        - gym==0.21.0
        - mujoco_py==2.0.2.5
        - box2d
        - absl-py
        - pygame
        - gtimer
        - joblib
        - git+https://github.com/rail-berkeley/d4rl@master#egg=d4rl
        - wandb
        - ml_collections
